function paramSet = setRtpParamset(rtp,Gains)

paramSet = Simulink.BlockDiagram.modifyTunableParameters(rtp, ...
            'GainFGLUst',               Gains( 1), ...
            'GainFVASst',               Gains( 2), ...
            'GainFSOLst',               Gains( 3), ...
            'GainFHAMst',               Gains( 4), ...
            'LceOffsetBFSHVASst',       Gains( 5), ...
            'GainLBFSHVASst',           Gains( 6), ...
            'LceOffsetBFSHst',          Gains( 7), ...
            'GainLBFSHst',              Gains( 8), ...
            'GainFGASst',               Gains( 9), ...
            'GainPhiHATHFLst',          Gains(10), ...
            'GainDphiHATHFLst',         Gains(11), ...
            'GainPhiHATGLUst',          Gains(12), ...
            'GainDphiHATGLUst',         Gains(13), ...
            'GainSGLUHAMst',            Gains(14), ...
            'GainSGLUcHFLst',           Gains(15), ...
            'GainSHAMcHFLst',           Gains(16), ...
            'GainSHFLcGLUst',           Gains(17),...%);
            'GainSRFcGLUst',            Gains(18), ...
            'LceOffsetTAst',            Gains(19), ...
            'GainLTAst',                Gains(20), ...
            'GainFSOLTAst',             Gains(21), ...
            'GainLTAsw',                Gains(22), ...
            'LceOffsetTAsw',            Gains(23), ...
            'GainLRFHFLsw',             Gains(24), ...
            'GainVRFHFLsw',             Gains(25), ...
            'GainLHAMGLUsw',            Gains(26), ...
            'GainVHAMGLUsw',            Gains(27), ...
            'GainVRFBFSHsw',            Gains(28), ...
            'GainVVASRFsw',             Gains(29), ...
            'GainVBFSHsw',              Gains(30), ...
            'GainLHAMsw',               Gains(31),...
            'GainSHAMBFSHsw',           Gains(32), ...
            'GainSHAMGASsw',            Gains(33), ...
            'SHAMthresholdsw',          Gains(34), ...
            'GainLHFLsw',               Gains(35), ...
            'GainLGLUsw',               Gains(36), ...
            'LceOffsetVASsw',           Gains(37), ...
            'GainLVASsw',               Gains(38), ...
            'legLengthClr',             Gains(39), ...
            'simbiconLegAngle0',        Gains(40), ...
            'simbiconGainD',            Gains(41), ...
            'simbiconGainV',            Gains(42), ...
            'deltaLegAngleThr',         Gains(43), ...
            'transSupst',               Gains(44), ...
            'transsw',                  Gains(45), ...
            'PreStimHFLst',             Gains(46), ...
            'PreStimGLUst',             Gains(47), ...
            'PreStimHAMst',             Gains(48), ...
            'PreStimRFst',              Gains(49), ...
            'PreStimVASst',             Gains(50), ...
            'PreStimBFSHst',            Gains(51), ...
            'PreStimGASst',             Gains(52), ...
            'PreStimSOLst',             Gains(53), ...
            'PreStimTAst',              Gains(54), ...
            'PreStimHFLsw',             Gains(55), ...
            'PreStimGLUsw',             Gains(56), ...
            'PreStimHAMsw',             Gains(57), ...
            'PreStimRFsw',              Gains(58), ...
            'PreStimVASsw',             Gains(59), ...
            'PreStimBFSHsw',            Gains(60), ...
            'PreStimGASsw',             Gains(61), ...
            'PreStimSOLsw',             Gains(62), ...
            'PreStimTAsw',              Gains(63), ...
            'phiHATref',                Gains(64), ...
            'vxInit',                   Gains(65), ...
            'LphiHip0',                 Gains(66), ...
            'LphiKnee0',                Gains(67), ...
            'LphiAnkle0',               Gains(68), ...
            'RphiHip0',                 Gains(69), ...
            'RphiKnee0',                Gains(70), ...
            'RphiAnkle0',               Gains(71), ...
            'LTargetAngleInit',         Gains(72), ...
            'LPreStimHFLinit',          Gains(73), ...
            'LPreStimGLUinit',          Gains(74), ...
            'LPreStimHAMinit',          Gains(75), ...
            'LPreStimRFinit',           Gains(76), ...
            'LPreStimVASinit',          Gains(77), ...
            'LPreStimBFSHinit',         Gains(78), ...
            'LPreStimGASinit',          Gains(79), ...
            'LPreStimSOLinit',          Gains(80), ...
            'LPreStimTAinit',           Gains(81), ...
            'RTargetAngleInit',         Gains(82), ...
            'RPreStimHFLinit',          Gains(83), ...
            'RPreStimGLUinit',          Gains(84), ...
            'RPreStimHAMinit',          Gains(85), ...
            'RPreStimRFinit',           Gains(86), ...
            'RPreStimVASinit',          Gains(87), ...
            'RPreStimBFSHinit',         Gains(88), ...
            'RPreStimGASinit',          Gains(89), ...
            'RPreStimSOLinit',          Gains(90), ...
            'RPreStimTAinit',           Gains(91), ...        
            'GainFHABst',               Gains(92), ...
            'GainPhiHATHABst',          Gains(93), ...
            'GainDphiHATHABst',         Gains(94), ...
            'GainPhiHATHADst',          Gains(95), ...
            'GainDphiHATHADst',         Gains(96), ...
            'GainSHABcHABst',           Gains(97), ...
            'GainSHADcHADst',           Gains(98), ...
            'GainLHABsw',               Gains(99), ...
            'GainLHADsw',               Gains(100), ...
            'simbiconLegAngle0_C',      Gains(101), ...
            'simbiconGainD_C',          Gains(102), ...
            'simbiconGainV_C',          Gains(103), ...
            'transSupst_C',             Gains(104), ...
            'transsw_C',                Gains(105), ...
            'PreStimHABst',             Gains(106), ...
            'PreStimHADst',             Gains(107), ...
            'PreStimHABsw',             Gains(108), ...
            'PreStimHADsw',             Gains(109), ...
            'vyInit',                   Gains(110), ...
            'rollInit',                 Gains(111), ...
            'LphiHipR0',                Gains(112), ...
            'RphiHipR0',                Gains(113), ...
            'LTargetAngleRInit',        Gains(114), ...
            'LPreStimHABinit',          Gains(115), ...
            'LPreStimHADinit',          Gains(116), ...
            'RTargetAngleRInit',        Gains(117), ...
            'RPreStimHABinit',          Gains(118), ...
            'RPreStimHADinit',          Gains(119));