function Obstacle = createObstacle()
CMGParams;

v = [obstacle_x, obstacle_y - obstacle_width/2, obstacle_z;...
    obstacle_x, obstacle_y + obstacle_width/2, obstacle_z;...
    obstacle_x, obstacle_y + obstacle_width/2, obstacle_z + obstacle_height;...
    obstacle_x, obstacle_y - obstacle_width/2, obstacle_z + obstacle_height;...
    obstacle_x + obstacle_depth, obstacle_y - obstacle_width/2, obstacle_z;...
    obstacle_x + obstacle_depth, obstacle_y + obstacle_width/2, obstacle_z;...
    obstacle_x + obstacle_depth, obstacle_y + obstacle_width/2, obstacle_z + obstacle_height;...
    obstacle_x + obstacle_depth, obstacle_y - obstacle_width/2, obstacle_z + obstacle_height];

f = [ 1,2,3,4; ... %front
    5,6,7,8; ... % back
    1,5,8,4; ... % y- side
    2,3,7,6; ... % y+ side
    3,4,8,7]; % top
Obstacle = patch('Faces',f,'Vertices',v,'FaceColor','green');
%         Obstacle = patch('Faces',f,'Vertices',v,'FaceColor',[1 1 0.8]);