function paramSet = setRtpParamsetCMG(rtp,Gains,prevParamSets)
if nargin < 3
    prevParamSets = [];
end
if isempty(prevParamSets)
    paramSet = Simulink.BlockDiagram.modifyTunableParameters(rtp, ...
        'RlegAngleFilter',       Gains( 1), ...
        'RkneeFlexSpeedGain',    Gains( 2), ...
        'RkneeFlexPosGain',      Gains( 3), ...
        'RkneeStopGain',         Gains( 4), ...
        'RkneeExtendGain',       Gains( 5), ...
        'TargetLegAngleTripFlex',Gains( 6), ...
        'RlegLengthClrTrip',     Gains( 7));
else
    paramSet = Simulink.BlockDiagram.modifyTunableParameters(prevParamSets, ...
        'RlegAngleFilter',       Gains( 1), ...
        'RkneeFlexSpeedGain',    Gains( 2), ...
        'RkneeFlexPosGain',      Gains( 3), ...
        'RkneeStopGain',         Gains( 4), ...
        'RkneeExtendGain',       Gains( 5), ...
        'TargetLegAngleTripFlex',Gains( 6), ...
        'RlegLengthClrTrip',     Gains( 7));
end