function paramSet = setRtpParamsetCMG(rtp,Gains,prevParamSets)
% SETTRPPARAMSETCMG         Function that creates a parameter set for the rapid accelerator mode
% INPUTS:
%   - rtp                   Rapid accelerator target of the model with CMG 
%   - Gains                 Gain values that should be inserted in the parameter set
%   - prevParamSets         Optional, another or previous created parameter set to which this parameter set should be included
%
% OUTPUTS:
%   - paramSet

%%
if nargin < 3
    prevParamSets = [];
end
if isempty(prevParamSets)
    paramSet = Simulink.BlockDiagram.modifyTunableParameters(rtp, ...
        'RlegAngleFilter',       Gains( 1), ...
        'RkneeFlexSpeedGain',    Gains( 2), ...
        'RkneeFlexPosGain',      Gains( 3), ...
        'RkneeStopGain',         Gains( 4), ...
        'RkneeExtendGain',       Gains( 5), ...
        'TargetLegAngleTripFlex',Gains( 6), ...
        'RlegLengthClrTrip',     Gains( 7));
else
    paramSet = Simulink.BlockDiagram.modifyTunableParameters(prevParamSets, ...
        'RlegAngleFilter',       Gains( 1), ...
        'RkneeFlexSpeedGain',    Gains( 2), ...
        'RkneeFlexPosGain',      Gains( 3), ...
        'RkneeStopGain',         Gains( 4), ...
        'RkneeExtendGain',       Gains( 5), ...
        'TargetLegAngleTripFlex',Gains( 6), ...
        'RlegLengthClrTrip',     Gains( 7));
end