BodyMechParams;
ControlParams;
% prostheticParams;

% load('Results/RoughDist/optimizedGains_novirtmuscle.mat');
% load('Results/RoughDist/optimizedGainsComb.mat');
LGainGAS           = Gains( 1);
LGainGLU           = Gains( 2);
LGainHAM           = Gains( 3);
LGainKneeOverExt   = Gains( 4);
LGainSOL           = Gains( 5);
LGainSOLTA         = Gains( 6);
LGainTA            = Gains( 7);
LGainVAS           = Gains( 8);
LKglu              = Gains( 9);
LPosGainGG         = Gains(10);
LSpeedGainGG       = Gains(11);
LhipDGain          = Gains(12);
LhipPGain          = Gains(13);
LkneeExtendGain    = Gains(14);
LkneeFlexGain      = Gains(15);
LkneeHoldGain1     = Gains(16);
LkneeHoldGain2     = Gains(17);
LkneeStopGain      = Gains(18);
LlegAngleFilter    = Gains(19);
LlegLengthClr      = Gains(20);
RGainGAS           = 0;
RGainGLU           = Gains(21);
RGainHAM           = 0;
RGainHAMCut        = Gains(22);
% RGainHAMCut        = Gains(24);
RGainKneeOverExt   = 0;
RGainSOL           = 0;
RGainSOLTA         = 0;
RGainTA            = 0;
RGainVAS           = 0;
RKglu              = Gains(23);
RPosGainGG         = Gains(24);
RSpeedGainGG       = Gains(25);
RhipDGain          = Gains(26);
RhipPGain          = Gains(27);
RkneeExtendGain    = Gains(28);
RkneeFlexGain      = Gains(29);
RkneeHoldGain1     = Gains(30);
RkneeHoldGain2     = Gains(31);
RkneeStopGain      = Gains(32);
RlegAngleFilter    = Gains(33);
RlegLengthClr      = Gains(34);
simbiconGainD      = Gains(35);
simbiconGainV      = Gains(36);
simbiconLegAngle0  = Gains(37);
legAngleTgt        = Gains(38);

%[groundX, groundZ, groundTheta] = generateGround('const',0.08,1);
[groundX, groundZ, groundTheta] = generateGround('flat');
